FROM python:3.8-slim

WORKDIR /usr/src/app

COPY ./frontend/requirements.txt ./
RUN pip install -r requirements.txt

COPY ./frontend ./frontend/
COPY ./frontend/wsgi.py ./
COPY ./env.d/frontend.env ./

ENV FLASK_ENV=development
CMD ["flask", "run", "--host=0.0.0.0"]
