version: "3"

services:

  frontend:
    image: cs-data-ingestion:frontend
    env_file: "env.d/frontend.env"
    volumes:
      - frontend-data:/cs-data-ingestion/frontend
    ports:
      - "5000:5000"
    deploy:
      replicas: 1

volumes:
  frontend-data: ~
